version: '3.8'

services:

  comfyui:
    init: true
    container_name: comfy3d-pt25
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:comfy3d-pt25"
    ports:
      - "8188:8188"
    volumes:
      - ./workspace:/root
      - ../Comfy3D_Pre_Builds/_Build_Wheels:/wheels:ro
    environment:
      - CLI_ARGS=--listen 0.0.0.0
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
