name: Build ComfyUI Docker Image

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    paths:
      - 'comfy3d-pt25/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NVIDIA Container Toolkit repository
        run: |
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
          curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
          sudo apt-get update

      - name: Install NVIDIA Container Toolkit
        run: |
          sudo apt-get install -y nvidia-container-toolkit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and save Docker image
        run: |
          cd comfy3d-pt25
          DOCKER_BUILDKIT=1 docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg CUDA_ARCHITECTURES="60 61 70 75 80 86" \
            -t yanwk/comfyui-boot:comfy3d-pt25 .
          docker save yanwk/comfyui-boot:comfy3d-pt25 > comfy3d-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: comfy3d-image
          path: comfy3d-pt25/comfy3d-image.tar
          compression-level: 0  # Don't compress as it's already a compressed tar 